Estructura del proyecto y Configuración Básica(Controllers, Models, Services)
rivaldo-ortega/MyLittleFriend-backend pull request #1
Opened 2022-01-20 03:01 UTC by Kasuk1

El siguiente PR contiene los diferentes cambios que se realizó en el backend.

La estructura fue inspirada en los ejemplos elaborados por el mentor y se trató de usar diversas técnicas mencionadas por el mismo.

La interacción de la API está dividida desde las Routes -> Controllers -> Models -> Services, con el objetivo de realizar un proyecto extendible a largo plazo.

2022-01-20 20:25 UTC, mhbuiles requested changes

2022-01-20 20:25 UTC, mhbuiles commented on app.js
> +const PORT = port || 4000;
Por qué no agregamos esta variable al archivo de variables de entorno .env?

2022-01-20 20:25 UTC, mhbuiles commented on controllers/customer.controller.js
> +        const isExists = await CustomerServices.findByEmail({ email });
Yo sugeriría cambiar el nombre de esta variable, isExist es algo redundante, los nombres de las variables deben ser disientes, qué es lo que existe o no?

2022-01-20 20:25 UTC, mhbuiles commented on controllers/pet.controller.js
> +    //const { name, detail, birthdate, type, avatar_url, owner } = req.body;
No dejemos líneas comentadas en nuestro código.

2022-01-20 20:25 UTC, mhbuiles commented on controllers/pet.controller.js
> +            data: {}
Me puedes aclarar por qué el objeto vacío en vez de enviar la data de la mascota registrada?

2022-01-20 20:25 UTC, mhbuiles commented on controllers/veterinary.controller.js
> +          data: {}
Por qué se retorna un objeto vacío? Veo que no hacemos nada con newVeterinary.

2022-01-20 20:25 UTC, mhbuiles commented on routes/pets.routes.js
> +
Una línea en blanco es suficiente.

2022-01-20 20:25 UTC, mhbuiles commented on services/attendace.services.js
> +    }catch(error){
Sería bueno dejar espacios: 

} catch (error) {

2022-01-20 20:25 UTC, mhbuiles commented on services/attendace.services.js
> +    }catch(error){
Sería bueno dejar espacios: 

} catch (error) {

2022-01-20 22:30 UTC, JeanMarco173 commented on app.js
> +const PORT = port || 4000;
Hola Mateo, la variable se guarda en el archivo .env . Lo que pasa es que se trae la variable del archivo de configuración.

2022-01-20 22:32 UTC, JeanMarco173 commented on controllers/pet.controller.js
> +            data: {}
No se utiliza la data de la mascota registrada. El cambio que tendríamos que hacer es usar status 201.

2022-01-20 22:33 UTC, JeanMarco173 commented on controllers/veterinary.controller.js
> +          data: {}
No se utiliza la data de la veterinaria registrada.

2022-01-21 23:05 UTC, mhbuiles approved these changes

2022-01-23 00:58 UTC, merged